### ISSUE TITLE
setup for development fail

### ISSUE THREAD

**Issue by binooetomo** [openwisp/django-freeradius#192]
Dear All.

I'm trying to follow steps from https://django-freeradius.readthedocs.io/en/latest/general/setup.html
I use 'pipenv' 

1. when 'pipenv install -r requirements-test.txt', I got traceback :
```
Requirements file provided! Importing into Pipfile...
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/cli.py", line 416, in install
    selective_upgrade=selective_upgrade,
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 1854, in do_install
    import_requirements(r=project.path_to(requirements), dev=dev)
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 228, in import_requirements
    project.recase_pipfile()
  File "/usr/lib/python2.7/site-packages/pipenv/project.py", line 766, in recase_pipfile
    if self.ensure_proper_casing():
  File "/usr/lib/python2.7/site-packages/pipenv/project.py", line 802, in ensure_proper_casing
    casing_changed = self.proper_case_section(pfile.get('packages', {}))
  File "/usr/lib/python2.7/site-packages/pipenv/project.py", line 826, in proper_case_section
    self.register_proper_name(new_casing)
  File "/usr/lib/python2.7/site-packages/pipenv/project.py", line 366, in register_proper_name
    f.write('{0}\n'.format(name))
TypeError: must be unicode, not str
/usr/lib/python2.7/site-packages/pipenv/_compat.py:108: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-HWaxHz-requirements'>
  warnings.warn(warn_message, ResourceWarning)

```

2. I step forward to './manage.py migrate', and got : 

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/bino/.local/share/virtualenvs/radx-In5vhZCB/lib/python3.6/site-packages/Django-2.1.2-py3.6.egg/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/bino/.local/share/virtualenvs/radx-In5vhZCB/lib/python3.6/site-packages/Django-2.1.2-py3.6.egg/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/bino/.local/share/virtualenvs/radx-In5vhZCB/lib/python3.6/site-packages/Django-2.1.2-py3.6.egg/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/home/bino/.local/share/virtualenvs/radx-In5vhZCB/lib/python3.6/site-packages/Django-2.1.2-py3.6.egg/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/bino/.local/share/virtualenvs/radx-In5vhZCB/lib/python3.6/site-packages/Django-2.1.2-py3.6.egg/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/bino/.local/share/virtualenvs/radx-In5vhZCB/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bino/radx/django-freeradius/tests/settings.py", line 4, in <module>
    import environ
  File "/home/bino/.local/share/virtualenvs/radx-In5vhZCB/lib/python3.6/site-packages/environ.py", line 114
    raise ValueError, "No frame marked with %s." % fname
                    ^
SyntaxError: invalid syntax

```

Sincerely
-bino-

**Comment by nemesisdesign** [comment]
It looks to me that you using python2, django-freeradius works with python3 only.

**Comment by binooetomo** [comment]
> It looks to me that you using python2, django-freeradius works with python3 only.

Sir,
I followed the instruction, i just replace 'virtualenvwrapper' with pipenv .. since I'm familiar with pipenv.

**Comment by nemesisdesign** [comment]
I see now `python3.6` in the path, sorry. I inferred a different issue because I saw a syntax error.

We have a build on python 3.6 which is working: https://travis-ci.org/openwisp/django-freeradius/jobs/444164660, so I'm not sure what's happening here.
