### ISSUE TITLE
[db] Smart migration from freeradius 3

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#41]
As discussed, we want to make it easy for those users who are already using freeradius 3 to start using django-freeradius.

To accomplish this we should proceed as follows:

1. [ ] first of all, we have to ensure our models reflect the default freeradius schema very closely
2. [ ] the first django migration should be dedicated to the default freeradius schema
3. [ ] every modification and addition to the default schema, must be done in subsequent migrations, starting from `0002`
4. [ ] we then need to document how to skip the first migration in case users want to use django-freeradius on an existing freeradius 3 database

**Comment by peppelinux** [comment]
With my last commit we are going to extend radius check table, I talking about here
https://github.com/openwisp/django-freeradius/pull/64

This means that freeradius have is_valid(boolean)  and valid_until(datetime) and a little patch in 
/etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf

according to what I already documented.
Yes I know that I did what shouldn't be done but it works and I also think that this feature improve in general the logic of freeradius check.

**Comment by nemesisdesign** [comment]
We have 3 fields of the radius check model that have to be added in subsequent migrations:

- ``is_active``
- ``valid_until``
- ``notes``

**Comment by rohithasrk** [comment]
Working on it.

**Comment by nemesisdesign** [comment]
@rohithasrk I can't run tests after merging the patch.. do you have any idea why?

```
Traceback (most recent call last):
  File "./runtests.py", line 16, in <module>
    execute_from_command_line(args)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/commands/test.py", line 26, in run_from_argv
    super().run_from_argv(argv)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/commands/test.py", line 59, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/test/runner.py", line 548, in setup_databases
    self.parallel, **kwargs
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/test/utils.py", line 176, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 68, in create_test_db
    run_syncdb=True,
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/__init__.py", line 141, in call_command
    return command.execute(*args, **defaults)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/migration.py", line 112, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/operations/models.py", line 241, in state_forwards
    state.remove_model(app_label, self.name_lower)
  File "/home/nemesis/.virtualenvs/openwisp2/lib/python3.5/site-packages/django/db/migrations/state.py", line 100, in remove_model
    del self.models[app_label, model_name]
KeyError: ('django_freeradius', 'radiusgroup')
```

**Comment by nemesisdesign** [comment]
@peppelinux @2stacks it would be helpful if you could help us ensuring patch #106 works
I want to remove the old migrations before we release the 0.1 version and I want to make sure you won't have problems when upgrading.

**Comment by nemesisdesign** [comment]
I'm removing the old migrations.

If anyone runs into problems with not being able to run `./manage.py migrate` after old migrations have been removed, you can try the following workaround:

```
git reset --hard <commit-where-both-migrations-are-present>
./manage.py migrate --fake django_freeradius zero
git pull origin master
./manage.py migrate --fake django_freeradius
```
